name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        teller:
          ["1.5.6"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Teller
        uses: ./
        with:
          teller-version: ${{ matrix.teller }}

      - name: Test
        run: npm run test
